### ISSUE TITLE
In `event_thread()`, shouldn't `vrd` be declared `static`?

### ISSUE THREAD

**Issue by cmcqueen** [konsulko/ws28xx-lighting-pru#2]
Because of the protothreads usage in the `RX_IN()` macro in `event_thread()`, it looks as though `vrd` needs to be declared `static`.

**Comment by mranostay** [comment]
Doesn't hurt for it be declared static, but looking through the calls it seems it doesn't go into a blocking function before vfd isn't referenced anymore. I'll double check with Pantelis since he was the original author of the prutest application which this is majorly based on.

**Comment by cmcqueen** [comment]
`RX_IN()` is a blocking function. The relevant lines are:

```
						vrd = pru_vring_desc(&rx_ring, idx);
						...
						while (len-- > 0)
							RX_IN(*ptr++);

						rx_len += vrd->len;
```

**Comment by mranostay** [comment]
Ah yes so it is :/. Surprised we didn't see any adverse effects from this.
Possibly it didn't show up since tx and rx didn't happen typically at the
same time.

**Comment by pantoniou** [comment]
Yes, vrd needs to be static. Good catch.

**Comment by mranostay** [comment]
Fixed!
